# Generated by Django 5.2.3 on 2025-06-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categorieproduit',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commande',
            name='id_client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='driveapp.client'),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='id_commande',
            field=models.ForeignKey(db_column='id_commande', on_delete=django.db.models.deletion.CASCADE, to='driveapp.commande'),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='id_produit',
            field=models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.CASCADE, to='driveapp.produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='commandeproduit',
            table='commande_produits',
        ),
    ]
